{{- if and .Values.receiver.enabled .Values.receiver.router.ingress.enabled -}}
{{- $apiIsStable := eq (include "shared.ingress.isStable" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "shared.ingress.supportsPathType" .) "true" -}}
{{- $serviceName := include "thanos.receiverRouter.fullname" . -}}
apiVersion: {{ include "shared.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $serviceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thanos.receiverRouter.labels" . | nindent 4 }}
  {{- with .Values.receiver.router.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if and $apiIsStable .Values.receiver.router.ingress.ingressClassName }}
  ingressClassName: {{ .Values.receiver.router.ingress.ingressClassName }}
{{- end }}
  rules:
  {{- range .Values.receiver.router.ingress.hosts }}
    - host: {{ quote . }}
      http:
        paths:
          - path: {{ printf "%s/api/v1/receive" $.Values.receiver.router.ingress.path | replace "//" "/" }}
            {{- if $ingressSupportsPathType }}
            pathType: Prefix
            {{- end }}
            backend:
            {{- if $apiIsStable }}
              service:
                name: {{ $serviceName }}
                port:
                  name: http-rem-write
            {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: http-rem-write
            {{- end }}
          - path: {{ $.Values.receiver.router.ingress.path }}
            {{- if $ingressSupportsPathType }}
            pathType: Prefix
            {{- end }}
            backend:
            {{- if $apiIsStable }}
              service:
                name: {{ $serviceName }}
                port:
                  name: http
            {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: http
            {{- end }}
  {{- end }}
{{- if .Values.receiver.router.ingress.tls }}
  tls:
  {{- range .Values.receiver.router.ingress.tls }}
    - hosts:
    {{- range .hosts }}
        - {{ quote . }}
    {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
{{- end }}
