{{- if and .Values.compactor.enabled .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "thanos.compactor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thanos.compactor.labels" . | nindent 4 }}
  {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  jobLabel: {{ .Values.serviceMonitor.jobLabel }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "thanos.compactor.selectorLabels" . | nindent 6 }}
    matchExpressions:
      - key: prometheus.io/service-monitor
        operator: NotIn
        values:
          - "false"
  endpoints:
    - port: http
    {{- if .Values.serviceMonitor.endpointConfig }}
      {{- toYaml .Values.serviceMonitor.endpointConfig | nindent 6 }}
    {{- else }}
    {{- end }}
{{- end -}}
