version: '3'

tasks:
  default:
    cmds:
      - task: help
  help:
    desc: "Show help"
    cmds:
      - task -l
  install-unittest:
    desc: Install unittest plugin
    cmd: helm plugin install https://github.com/helm-unittest/helm-unittest.git
  test:
    desc: Run unit tests
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - helm unittest --failfast -f 'tests/*.yaml' .
  template:
    desc: Run template with lint values into _template.yaml file
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - helm template $(basename "$PWD") . -f lint-values.yaml > _template.yaml
  template_debug:
    desc: Run template with lint values into _template.yaml file with debug option
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - helm template $(basename "$PWD") . -f lint-values.yaml --debug > _template.yaml
  template-cli:
    desc: Run template with custom values provided as CLI parameter into _template.yaml file
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - helm template $(basename "$PWD") . -f {{.CLI_ARGS}} > _template.yaml
  docs: ## https://github.com/norwoodj/helm-docs?tab=readme-ov-file
    desc: Generate helm docs
    cmds:
      - helm-docs --template-files=./_templates.gotmpl --template-files=./_chart-readme.md.gotmpl -l debug
  pre-commit-helm-docs:
    desc: Run pre-commit hook for helm-docs
    cmds:
      - pre-commit run helm-docs-container --all-files
  act:
    desc: Run act
    cmds:
      - act --container-architecture linux/amd64
  act-ci-pipeline:
    desc: Run act ci-pipeline workflow
    cmds:
      - act --container-architecture linux/amd64 -W ".github/workflows/ci-pipeline.yml"
  act-helm-publish:
    desc: Run act helm-publish workflow
    cmds:
      - act pull_request --container-architecture linux/amd64 -W '.github/workflows/helm-publish.yml' -s GITHUB_TOKEN="$(gh auth token)"
  act-pr-validate:
    desc: Run act pr-validate workflow
    cmds:
      - act pull_request --container-architecture linux/amd64 -W '.github/workflows/pr-validate.yml'
  run-renovate-extract:
    desc: Run renovate extract only
    cmds:
      - docker run --rm -e RENOVATE_PLATFORM=local -e RENOVATE_DRY_RUN=extract -v $(pwd):/usr/src/app  renovate/renovate:latest
  run-renovate-full:
    desc: Run renovate full
    cmds:
      - docker run --rm -e RENOVATE_PLATFORM=local -e RENOVATE_DRY_RUN=full -e LOG_LEVEL=debug -v $(pwd):/usr/src/app  renovate/renovate:latest
  ct-install:
    desc: Run chart-testing tool locally
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - ct install --chart-dirs . --charts . --debug
