{{- if and .Values.ruler.enabled .Values.ruler.alertmanagersConfig.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thanos.ruler.alertmanagersConfigSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thanos.ruler.labels" . | nindent 4 }}
data:
  {{ .Values.ruler.alertmanagersConfig.key }}: |-
    {{- .Values.ruler.alertmanagersConfig.value | b64enc | nindent 4 }}
{{- end -}}
