{{- if and (and .Values.bucketweb.enabled .Values.bucketweb.autoscaling.enabled) (or .Values.bucketweb.autoscaling.targetCPUUtilizationPercentage .Values.bucketweb.autoscaling.targetMemoryUtilizationPercentage) -}}
apiVersion: {{ include "shared.hpa.apiVersion" . }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "thanos.bucketweb.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thanos.bucketweb.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "thanos.bucketweb.fullname" . }}
  minReplicas: {{ .Values.bucketweb.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.bucketweb.autoscaling.maxReplicas }}
  metrics:
  {{- with .Values.bucketweb.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ . }}
  {{- end }}
  {{- with .Values.bucketweb.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ . }}
  {{- end }}
{{- end -}}
