{{- if or (not .Values.auth.existingRootPasswordSecret) (not .Values.auth.existingRootUsernameSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if (not .Values.auth.existingRootUsernameSecret) }}
  {{- if .Values.auth.rootUsername }}
  root-user: {{ .Values.auth.rootUsername | b64enc | quote }}
  {{- else }}
  root-user: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if (not .Values.auth.existingRootPasswordSecret) }}
  {{- if .Values.auth.rootPassword }}
  root-password: {{ .Values.auth.rootPassword | b64enc | quote }}
  {{- else }}
  root-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
