{{- if .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "rabbitmq.peerDiscoveryRoleName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "rabbitmq.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "rabbitmq.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "rabbitmq.peerDiscoveryRoleName" . }}
{{- end }}
