{{- if or (not .Values.auth.existingPasswordSecret) (not .Values.auth.existingErlangCookieSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if (not .Values.auth.existingPasswordSecret) }}
  {{- if .Values.auth.password }}
  password: {{ .Values.auth.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if (not .Values.auth.existingErlangCookieSecret) }}
  {{- if .Values.auth.erlangCookie }}
  erlang-cookie: {{ .Values.auth.erlangCookie | b64enc | quote }}
  {{- else }}
  erlang-cookie: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
