{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.auth.password }}
  password: {{ .Values.auth.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.erlangCookie }}
  erlang-cookie: {{ .Values.auth.erlangCookie | b64enc | quote }}
  {{- else }}
  erlang-cookie: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
