apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.amqp }}
      targetPort: amqp
      protocol: TCP
      name: amqp
    {{- if .Values.managementPlugin.enabled }}
    - port: {{ .Values.service.ports.mgmt }}
      targetPort: mgmt
      protocol: TCP
      name: mgmt
    {{- end }}
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
      name: metrics
    {{- end }}
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
