apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.serviceNameHeadless" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.service.ports.amqp }}
      targetPort: amqp
      name: amqp
    - port: {{ .Values.service.ports.epmd }}
      targetPort: epmd
      name: epmd
    - port: {{ .Values.service.ports.dist }}
      targetPort: dist
      name: dist
    {{- if .Values.managementPlugin.enabled }}
    - port: {{ .Values.service.ports.mgmt }}
      targetPort: mgmt
      name: mgmt
    {{- end }}
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
