name: CI Pipeline
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: d3adb5/helm-unittest-action@v2
        name: Run unit tests
        with:
          helm-version: v3.18.6
          github-token: ${{ secrets.GITHUB_TOKEN }}
          install-mode: if-not-present
      - name: Template lint values
        run: |
          for chart_dir in charts/*/; do
            if [ -d "$chart_dir" ]; then
              chart=$(basename "$chart_dir")
              echo "Processing chart: $chart"
              cd "$chart_dir"
              # Template lint values if lint-values.yaml exists
              if [ -f lint-values.yaml ]; then
                echo "Templating lint values for $chart..."
                helm template "$chart" . -f lint-values.yaml > _template.yaml
                echo "🟢 Successfully templated values for $chart..."
              else
                echo "🟡 No lint-values.yaml found for $chart, skipping template validation"
              fi
              cd - > /dev/null
            fi
          done
